### PR TITLE
Archery Categories Expanded

### PR DESCRIPTION
**Pull request by sayscraig**
Updated to adjust the archery category structure and add some additional archery categories that are necessary. 

At Editions.dev I spoke to someone about Shopify working with some merchants in niche industries to help expand the categories and was hoping to make contact with someone there to discuss the archery niche since we are the largest merchant in the industry. Please let me know if that is possible.

### CODE REVIEW

**Comment by sayscraig** [comment]
I have signed the CLA!

**Comment by ricardotejedorsanz** [comment]
@sayscraig First, thank you for your incredible contributions. We're currently working on integrating these suggestions to ensure consistency across our taxonomy. Please bear with us as we implement these changes in upcoming updates! In the meantime, do you have any links we could take a look at to support these changes? I'd also be more than happy to schedule a chat if you have a few minutes to spare 😄

**Comment by sayscraig** [comment]
@ricardotejedorsanz I would love to chat, that would be fantastic. What is the best way to connect?

Here are a couple links as well.

Filters show archery styles: https://lancasterarchery.com/collections/arrows
Menu on the website will also show the breakdown of categories into the categories I have added like mechanical/fixed blade broadheads, expanded Bow & Crossbow accessories categories, and all the others.

**Comment by ricardotejedorsanz** [comment]
Hi @sayscraig, thanks again for chatting with me the other day!

Suggesting a few changes following our discussion:

- New attributes for Archery target types instead of categories
- ID changes for consistency within our tree
- Created a Broadhead type attribute instead of categories to avoid going as deep as L8 in the tree (hope this is alright!)

Please let me know if you have any comments, and bear with us while we work on making these changes available in our next taxonomy release.

**Comment by ricardotejedorsanz** [comment]
fyi @elsom25 @tylerrowsell @KComrade53 placeholder [commit](https://github.com/Shopify/product-taxonomy/pull/229/commits/f66193376066fc7e8d991adcc5d5963afe3f5991) with a few tweaks, pending changes to the `./integrations` files for the next release. Also pending new attribute descriptions + translations.

**Comment by ricardotejedorsanz** [comment]
I have signed the CLA!

**Comment by sayscraig** [comment]
@ricardotejedorsanz those updates sounds great to me. I agree with the broadhead type as well, that was a good call.

**Comment by elsom25** [comment]
@sayscraig at this point I'd say its on us — selfishly I want to use this to test a few "tools" we're adding to the repo as well to see if they help with these kinds of things. 

It will certainly be addressed before our next version cutoff

**Comment by sayscraig** [comment]
@elsom25 Hi just checking in since I assume we are getting close to the release of these changes. Hoping to confirm that the plan is still for this PR to get merged and released soon?

**Comment by ricardotejedorsanz** [comment]
Moving to https://github.com/Shopify/product-taxonomy/pull/391 to override merging issue.

**Pull request closed without merging**
