### PR TITLE
Fix README link + update for localization fixes

### PR DESCRIPTION
**Pull request by ricardotejedorsanz**
1. Fix README link for taxonomy tree requests following rename to `1-taxonomy-tree-requests.yml`

2. Add link to localization fix issue template [**Option 1**]

- Alternatively, we could add a new sub-section under `2. Taxonomists: How to make changes to the taxonomy` [**Option 2**]. Or a README with further guidance in the `localizations` directory?

### 🧑🏼‍🏫 2. Taxonomists: How to make changes to the taxonomy

Submit a [taxonomy tree change request](https://github.com/Shopify/product-taxonomy/issues/new?labels=taxonomy-tree-requests&projects=&template=taxonomy-tree-requests.yml&title=%5BTaxonomy+Tree%5D%3A+) to give us insight and evolve the taxonomy. This is the simplest way to effect change.

Alternatively, you may submit PRs directly yourself against the source-of-truth files in [`data/`](./data).

If you make changes to any files in [`data/`](./data), you'll need to update the distribution files. There are two ways:
1. Make a PR comment of `/generate_dist` to have CI commit the changes for you 🤖
2. Run `make` locally and commit the changes yourself

### 🧑🏼‍🏫 2. Taxonomists: How to make changes to the taxonomy

Submit a [taxonomy tree change request](https://github.com/Shopify/product-taxonomy/issues/new?template=1-taxonomy-tree-requests.yml) to give us insight and evolve the taxonomy. This is the simplest way to effect change. For translation issues (non-English text), submit a [localization fix request](https://github.com/Shopify/product-taxonomy/issues/new?template=2-localization-fix-requests.yml) instead.

Alternatively, you may submit PRs directly yourself against the source-of-truth files in [`data/`](./data).

If you make changes to any files in [`data/`](./data), you'll need to update the distribution files. There are two ways:
1. Make a PR comment of `/generate_dist` to have CI commit the changes for you 🤖
2. Run `make` locally and commit the changes yourself

### 🧑🏼‍🏫 2. Taxonomists: How to make changes to the taxonomy

Submit a [taxonomy tree change request](https://github.com/Shopify/product-taxonomy/issues/new?template=1-taxonomy-tree-requests.yml) to give us insight and evolve the taxonomy. This is the simplest way to effect change.

Alternatively, you may submit PRs directly yourself against the source-of-truth files in [`data/`](./data).

If you make changes to any files in [`data/`](./data), you'll need to update the distribution files. There are two ways:
1. Make a PR comment of `/generate_dist` to have CI commit the changes for you 🤖
2. Run `make` locally and commit the changes yourself

#### 🌐 Localization to other languages

Our taxonomy supports translations to various languages in the `localizations` directory. To report a translation issue (non-English text), submit a [localization fix request](https://github.com/Shopify/product-taxonomy/issues/new?template=2-localization-fix-requests.yml).

### CODE REVIEW

**Review by elsom25 — APPROVED** [review]
Change looks good. I kinda like option 2, but curious on others thoughts on if simpler is better here

**Comment by ricardotejedorsanz** [comment]
> Change looks good. I kinda like option 2, but curious on others thoughts on if simpler is better here

@tylerrowsell @aalexandreia @MRodriguezRod any thoughts? :)

**Comment by aalexandreia** [comment]
@ricardotejedorsanz They both look good to me, but I like the second option a bit more too. It seems a bit more clear for someone who is looking to report a translation issue.

**Review by tylerrowsell — APPROVED** [review]
+1 to option 2

**Pull request merged**
